# コメントは日本語で OK
Style/AsciiComments:
  Enabled: false

# 行の文字数を制限しない
Layout/LineLength:
  Enabled: false

# クラスの長さを制限しない
Metrics/ClassLength:
  Enabled: false

# メソッドの長さを制限しない
Metrics/MethodLength:
  Enabled: false

# 複雑なメソッド OK
Metrics/AbcSize:
  Enabled: false

# 複雑なメソッド OK
Metrics/CyclomaticComplexity:
  Enabled: false

# 複雑なメソッド OK
Metrics/PerceivedComplexity:
  Enabled: false

# メソッドのパラメータに x のような短い名前を使う
Naming/MethodParameterName:
  Enabled: false
